# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
    Settings.setObjectName("Settings")
    Settings.setEnabled(True)
    Settings.resize(452, 340)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
    Settings.setSizePolicy(sizePolicy)
    Settings.setModal(True)
    self.outerGrid = QtWidgets.QGridLayout(Settings)
    self.outerGrid.setObjectName("outerGrid")
    self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
    self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
    self.buttonBox.setObjectName("buttonBox")
    self.outerGrid.addWidget(self.buttonBox, 6, 3, 1, 1)
    self.version = QtWidgets.QLabel(Settings)
    self.version.setObjectName("version")
    self.outerGrid.addWidget(self.version, 6, 0, 1, 2)
    self.gridLayout = QtWidgets.QGridLayout()
    self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
    self.gridLayout.setVerticalSpacing(3)
    self.gridLayout.setObjectName("gridLayout")
    self.jishoLabel = QtWidgets.QLabel(Settings)
    self.jishoLabel.setObjectName("jishoLabel")
    self.gridLayout.addWidget(self.jishoLabel, 0, 0, 1, 1)
    self.jishoTrigger = QtWidgets.QKeySequenceEdit(Settings)
    self.jishoTrigger.setObjectName("jishoTrigger")
    self.gridLayout.addWidget(self.jishoTrigger, 0, 1, 1, 1)
    self.wikipediaLabel = QtWidgets.QLabel(Settings)
    self.wikipediaLabel.setObjectName("wikipediaLabel")
    self.gridLayout.addWidget(self.wikipediaLabel, 1, 0, 1, 1)
    self.wikipediaTrigger = QtWidgets.QKeySequenceEdit(Settings)
    self.wikipediaTrigger.setObjectName("wikipediaTrigger")
    self.gridLayout.addWidget(self.wikipediaTrigger, 1, 1, 1, 1)
    self.languageLabel = QtWidgets.QLabel(Settings)
    self.languageLabel.setObjectName("languageLabel")
    self.gridLayout.addWidget(self.languageLabel, 2, 0, 1, 1)
    self.languageSelector = QtWidgets.QComboBox(Settings)
    self.languageSelector.setMaxVisibleItems(10)
    self.languageSelector.setObjectName("languageSelector")
    self.gridLayout.addWidget(self.languageSelector, 2, 1, 1, 1)
    self.backsideLabel = QtWidgets.QLabel(Settings)
    self.backsideLabel.setObjectName("backsideLabel")
    self.gridLayout.addWidget(self.backsideLabel, 3, 0, 1, 1)
    self.checkBox = QtWidgets.QCheckBox(Settings)
    self.checkBox.setText("")
    self.checkBox.setObjectName("checkBox")
    self.gridLayout.addWidget(self.checkBox, 3, 1, 1, 1)
    self.outerGrid.addLayout(self.gridLayout, 0, 0, 2, 4)
    self.infoLabel = QtWidgets.QLabel(Settings)
    self.infoLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
    self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
    self.infoLabel.setWordWrap(True)
    self.infoLabel.setObjectName("infoLabel")
    self.outerGrid.addWidget(self.infoLabel, 5, 1, 1, 3)

    self.retranslateUi(Settings)
    self.languageSelector.setCurrentIndex(-1)
    self.buttonBox.accepted.connect(Settings.accept) # type: ignore
    self.buttonBox.rejected.connect(Settings.reject) # type: ignore
    QtCore.QMetaObject.connectSlotsByName(Settings)

def retranslateUi(self, Settings):
    _translate = QtCore.QCoreApplication.translate
    Settings.setWindowTitle(_translate("Settings", "JishoLookup config"))
    self.version.setText(_translate("Settings", "V 1.0.0"))
    self.jishoLabel.setToolTip(_translate("Settings", "The keyboard shortcut for Jisho lookup"))
    self.jishoLabel.setText(_translate("Settings", "Jisho shortcut"))
    self.jishoTrigger.setToolTip(_translate("Settings", "Left-click and choose key combo, then hit enter"))
    self.wikipediaLabel.setToolTip(_translate("Settings", "The keyboard shortcut for Wikipedia lookup (fallback)"))
    self.wikipediaLabel.setText(_translate("Settings", "Wikipedia shortcut"))
    self.wikipediaTrigger.setToolTip(_translate("Settings", "Left-click and choose key combo, then hit enter"))
    self.languageLabel.setToolTip(_translate("Settings", "The language wiki in which the add-on will look up the selected word(s)"))
    self.languageLabel.setText(_translate("Settings", "Wikipedia language"))
    self.languageSelector.setToolTip(_translate("Settings", "The language wiki in which the add-on will look up the selected word(s)"))
    self.backsideLabel.setToolTip(_translate("Settings", "Whether to always show the lookup pop-up or only when card is flipped"))
    self.backsideLabel.setText(_translate("Settings", "Only trigger if card is flipped?"))
    self.infoLabel.setText(_translate("Settings", "For changes to apply, please reinitialize deck (go back to deck picker and reopen your study deck)"))